### ISSUE TITLE
WHERE and BETWEEN function not possible with new called columns

### ISSUE THREAD

**Issue by dieterdewachter** [vives-databases-2020/databases-practical#4]
ERROR 1054 (42S22): Unknown column 'total_score' in 'where clause'

**Comment by dieterdewachter** [comment]
use HAVING in place of WHERE

**Comment by sillevl** [comment]
https://github.com/sillevl/course-databases/blame/master/src/chapters/05-retreiving-data/calculated-fields/index.md#L101-L123
